version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  app:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "1337:1337"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

volumes:
    mongo_data:
